apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: minecraft
          image: 731401215014.dkr.ecr.us-east-1.amazonaws.com/mc-server:mc-1.21.1-build1
          ports:
            - containerPort: 25565
          envFrom:
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
